# Artalk Config File
## For more information: https://artalk.js.org

artalk:
  enable: false

  # Backend server API, you should set this to your own server API
  server: https://artalk.example.com

  # Site name, you can set this to specify site for server
  # or leave blank to use default site
  site:

  # Frontend resources CDN, you can set this to your preferred CDN
  ## Reference: https://artalk.js.org/guide/frontend/install.html
  jsUrl: https://unpkg.com/artalk@2/dist/Artalk.js
  cssUrl: https://unpkg.com/artalk@2/dist/Artalk.css

  # Page views count
  pvCount: true

  # Comments count
  commentCount: true

  # Dark mode
  darkMode: auto

  # Use backend to config
  ## Reference: https://artalk.js.org/guide/backend/fe-control.html
  useBackendConf: false